#ifndef __GAME_CONSTANTS
#define __GAME_CONSTNATS

#define PLAYER_FLOOR 1.2
#define PLAYER_SCALE 275

#define LEDGEBOX_WIDTH 0.18
#define LEDGEBOX_HEIGHT 0.18
#define LEDGEBOX_BASE 0.19

#define PLAYER_ECB_OFFSET Pair(0, -0.2)

#endif